### ISSUE TITLE
Failing to install NPM Global Packages CentOS 7

### ISSUE THREAD

**Issue by zuzsso** [geerlingguy/ansible-role-nodejs#105]
At some point running the playbook, the process fail at step `Ensure npm global packages are installed.`. 

In my `vars` file, I have the following configuration: 

```
nodejs_version: "8.x"

nodejs_npm_global_packages:
  - name: node-sass
```

The execution of the playbook fails at step _Ensure npm global packages are installed_ with error `...Error: EACCES: permission denied, mkdir '/usr/local/lib/npm/lib/node_modules/node-sass/vendor'...`

The error is a bit misleading because the command `mkdir /usr/local/lib/npm/lib/node_modules/node-sass/vendor` also fails if I executed it manually as super user. However, `mkdir -p /usr...` works fine. In fact, if I add a new instruction on the playbook to create that directory *recursively* before executing the _node js_ role, it works fine.

**Comment by glaszig** [comment]
this looks like a permission issue on your host.

the step "Ensure npm global packages are installed" runs through npm directly and the error "EACCES: permission denied" (which is thrown by npm) indicates that npm is run by a user that has to permissions for a folder along the path. npm internally uses a variant of "mkdir -p" so that's not the issue.

is your playbook running as root? with sudo? without a privileged user? if the latter, make sure the unprivileged user has access to that path.

**Comment by mauriciovillam** [comment]
I have exactly the same issue, running the playbook as sudo.
