### ISSUE TITLE
Node 5.x versions may not work correctly with debian_repo_version logic

### ISSUE THREAD

**Issue by fubarhouse** [geerlingguy/ansible-role-nodejs#12]
It seems like development is moving real quick with this one, but nodesource have provided support to the latest stable release of nodejs (v5.0.0).

It's not actually released yet, so this could be completely premature, but I feel the need to at least point it out to you. This is exactly why I personally use NVM over nodesource.

Source of the compatibility upgrade:
https://github.com/nodesource/distributions/commit/485c93c917bf9eb20ee3f960e70557f998723d32

**Comment by geerlingguy** [comment]
Yeah :(

I just added a fix in #10 that makes sure 4.x versions are fully supported... but that fix might not allow 5.x versions to work correctly if specified like "5.1" (once that version exists).

**Comment by jbouzekri** [comment]
I confirm that it does not work. Mainly because of the star in "Ensure Node.js and npm are installed.". Would you consider removing this star ? or allow playbook to specify its own debian_repo_version for example by adding a when: debian_repo_version is undefined condition in the task "Configure Debian repo version" ?

Thanks in advance

**Comment by geerlingguy** [comment]
@jbouzekri - Can you test #16 and see if that works for you?

**Comment by jbouzekri** [comment]
Okay. I will test it this evening and give you a feedback.
Thanks

**Comment by jbouzekri** [comment]
It worked like a charm. ^^

**Comment by geerlingguy** [comment]
This should be fixed by #16
