### ISSUE TITLE
Issue with permissions on Travis install

### ISSUE THREAD

**Issue by nerdstein** [geerlingguy/ansible-role-nodejs#13]
Set `ansible-playbook -i tests/inventory tests/$SITE --connection=local --sudo` in .travis.yml

In tests/test.yml:

``
hosts: localhost
  remote_user: root

  roles:
    - geerlingguy.nodejs
    - ansible-role-pa11y
``

Oddly, throwing the following error:

``
TASK [geerlingguy.nodejs : Add NodeSource repositories for Node.js.] ***********
changed: [localhost] => (item=deb https://deb.nodesource.com/node_0.10 precise main)
failed: [localhost] => (item=deb-src https://deb.nodesource.com/node_0.10 precise main) => {"failed": true, "item": "deb-src https://deb.nodesource.com/node_0.10 precise main", "msg": "[Errno 13] Permission denied: '/etc/apt/sources.list.d/.deb_nodesource_com_node_0_10.list-816YUw'"}
``

I also tried this within tests/test.yml:

`{role: geerlingguy.nodejs, become: yes}`

No dice.

**Comment by nerdstein** [comment]
@geerlingguy sorry to harass, did you have a chance to glance at this?

**Comment by geerlingguy** [comment]
@nerdstein - :( Sorry still not able to get to this right now, but might very soon... going through my biannual culling of all my roles in Galaxy this week.

**Comment by nerdstein** [comment]
+1 thanks @geerlingguy

**Comment by geerlingguy** [comment]
@nerdstein - So, finally got a chance to check this out... something in Travis CI's build system has changed that is protecting certain directories (even if you use sudo), and so I've switched many of my roles to a Docker-based testing setup; see this repositories master branch, the `tests` directory and `.travis.yml`.

Using this setup, I don't have to worry anymore about the strange changes that Travis goes through with the build environment all the time—plus I can test any Dockerizable platform instead of just Ubuntu 12.04 :)
